app/models/__init__.py
from .card import Card

app/models/card.py
from app import DB as db

class Card(db.Model):

    radicado = db.Column(db.String(50), unique=True, nullable=False, primary_key=True)
    
    placa_vehiculo = db.Column(db.String(50), unique=False, nullable=False)
    tarjeta_vehiculo = db.Column(db.String(50), unique=False, nullable=False)

    numero_tarjeta_operacion = db.Column(db.String(100), unique=False, nullable=False)
    fecha_vencimiento = db.Column(db.String(50), unique=False, nullable=False)
    fecha_inicio_vigencia = db.Column(db.String(50), unique=False, nullable=False)
    fecha_fin_vigencia = db.Column(db.String(50), unique=False, nullable=False)

    tipo_documento_conductor = db.Column(db.String(50), unique=False, nullable=False)
    documento_conductor = db.Column(db.String(50), unique=False, nullable=False)
    nombre_conductor = db.Column(db.String(200), unique=False, nullable=False)
    licencia_conductor = db.Column(db.String(200), unique=False, nullable=False)

app/__init__.py
'''
Initial Module for start and set up the Flask Appliaction
'''
import logging
from flask import Flask, render_template
from werkzeug.exceptions import HTTPException
from flask_sqlalchemy import SQLAlchemy
from iota import Iota

error_logger = logging.getLogger('error_logger')
DB = None

def create_app():
    # Instantiate app.
    app = Flask(__name__)

    with app.app_context():
        # Set app configuration
        config(app)

        # Define app db
        set_db(app)

        # Define API CLient
        api_client(app)

        # Register app routes.
        register_routes(app)

        # Handle app errors
        handle_errors(app)

        global DB
        DB.create_all()

    return app


def config(app):
    # Define app config
    app.config.from_object('config')


def set_db(app):
    global DB
    DB = SQLAlchemy(app)
    DB.init_app(app)

def api_client(app):
    api = Iota(app.config['API_PATH'], testnet=True)
    app.config['API_CLIENT'] = api


def register_routes(app):
    # Import views as blueprints
    from .views import Home, Card

    # Register blueprints.
    app.register_blueprint(Home)
    app.register_blueprint(Card, url_prefix='/cards')

def handle_errors(app):
    # Error handlers.
    error_template = 'error.html'

    @app.errorhandler(HTTPException)
    def handle_http_error(e):
        error_logger.error('EXCEPTION: '+str(e), exc_info=True)
        return render_template(error_template, error=e), e.code

    @app.errorhandler(Exception)
    def handle_exception(e):
        error_logger.error('EXCEPTION: '+str(e), exc_info=True)
        err = {
            'code': 500, 
            'name': 'Internal Server Error',
            'description': 'An Error has occurred on the application server, you might contact the administrator for more information'
        }
        return render_template(error_template, error=err, exception=True), 500

app/views/__init__.py
from .home import Home
from .card import Card

app/views/card.py
import secrets
from random import randint

from flask import Blueprint, render_template, flash, session, current_app, request, redirect, url_for

from app.logic.dag_transaction import read_card, write_card
from app.logic.log_cards import set_cards_log, get_cards_log
from app.logic.db_card import create_card, select_card
from app.utils.constants import dni_types

Card = Blueprint('card', __name__)

APP_CONFIG = current_app.config
iota_api = APP_CONFIG['API_CLIENT']
iota_address = APP_CONFIG['ADDRESS']


@Card.route('/registry', methods=['GET', 'POST'])
def registry():
    form = request.form.to_dict()
    method = request.method
    if method == 'POST' and form:
        return registry_transaction(form)
    else:
        radicado = secrets.token_hex(nbytes=randint(10, 12))
        return render_template(
            'registry.html',
            radicado=radicado.upper(),
            dni_types=dni_types
        )


def registry_transaction(form):
    write = write_card(iota_api, iota_address, form)
    create = create_card(form)
    if write and create:
        set_cards_log(form['radicado'], write)
    
    return redirect(url_for('card.explorer'))



@Card.route('/explorer', methods=['GET'])
def explorer():
    tangle_log_list = get_cards_log()
    return render_template('explorer.html', transaction_list=tangle_log_list)


@Card.route('/detail/<query_type>/<identifier>', methods=['GET'])
def detail(query_type, identifier):
    card = {}
    tail_transaction_hash = None

    if query_type == 'tangle':
        tail_transaction_hash = identifier
        card = read_card(iota_api, tail_transaction_hash)
    elif query_type == 'db':
        radicado = identifier
        card = select_card(radicado)

    return render_template('detail.html', card=card, tail_transaction_hash=tail_transaction_hash)

app/views/home.py
from flask import Blueprint, render_template, flash, session, current_app, request, redirect

Home = Blueprint('home', __name__)


@Home.route('/', methods=('GET', 'POST'))
def index():
    return render_template('index.html')

app/templates/components/footer.html
<div class="abc-loading" id="loading">
  <div class="spinner-border text-light" role="status">
    <span class="sr-only">Cargando...</span>
  </div>
  <span class="text-light font-weight-bold my-4">
    Espere por favor...
  </span>
</div>

<!-- Footer-->
<footer class="d-none">
  <div class="container-fluid bg-light py-5 d-flex justify-content-center">
    <div>
      <div class="row d-flex justify-content-center pl-5">

        <div class="col-4">
          <h6 id='about' class="text-uppercase font-weight-bold mb-4">Acerca de</h6>
          <p class="font-italic text-muted">
            IOTA es una tecnología de contabilidad distribuida de código abierto, cuyo
            objetivo es permitir de forma segura el intercambio de warningrmación y valor en el Internet de las Cosas.
          </p>
        </div>
        <div class="col-3">
          <h6 class="text-uppercase font-weight-bold mb-4">Accesos rapidos</h6>
          <ul class="list-unstyled mb-0">
            <li class="mb-2">
              <a class="text-muted" href="{{url_for('card.explorer')}}"
                title="Explorador de transacciones">Explorador</a>
            </li>
            <li class="mb-2">
              <a class="text-muted" href="{{url_for('card.registry')}}" title="Registro de transacción">Registro</a>
            </li>
          </ul>
        </div>
        <div class="col-3">
          <h6 class="text-uppercase font-weight-bold mb-4">Redes Sociales</h6>
          <ul class="list-unstyled mb-0">
            <li class="list-item"><a href="https://facebook.com" target="_blank" title="facebook"><span
                  class="fa fa-facebook">Facebook</span></a>
            </li>
            <li class="list-item"><a href="https://twitter.com" target="_blank" title="twitter"><span
                  class="fa fa-twitter"></span>Twitter</a>
            </li>
            <li class="list-item"><a href="https://instagram.com" target="_blank" title="instagram"><span
                  class="fa fa-instagram"></span>Instagram</a></li>
          </ul>
        </div>
      </div>
      <!-- Copyrights -->
      <br>
      <div class="text-center">
        <p class="text-muted mb-0 py-2">&copy;{{config.CURRENT_YEAR}} {{ config.APP_NAME }} | Todos los derechos
          reservados.</p>
      </div>
    </div>
  </div>

</footer>

<!-- scripts -->
<script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->
<script src="{{ url_for('static', filename='main.js') }}" type="text/javascript"></script>
{% block scripts %}{% endblock %}


</body>

</html>

app/templates/components/header.html
<!-- Header -->
<header>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-sm navbar-light bg-warning">
    <div class="container">
      <!-- Navbar Brand -->
      <a class="navbar-brand font-otalic" href="{{ url_for('home.index') }}">
        <img class="d-none d-md-inline" src="{{ url_for('static', filename='img/logo.png') }}" alt="" height="10%" width="10%">
        {{ config.APP_NAME }}
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <!-- Main Navigation -->
      
        <ul class="navbar-nav ml-auto">

          <li class="nav-item">
            <a class="nav-link text-dark" href="{{url_for('card.explorer')}}" title="Explorador de transacciones">Explorador</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark" href="{{url_for('card.registry')}}" title="Registro de transacción">Registro</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>
</header>

app/templates/components/messages.html
<!-- Flash Messages -->
{% with messages = get_flashed_messages(with_categories=true) %}

    {% if messages %}

        {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismisible">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <p class="d-none d-sm-inline d-sm-none m-0 p-0">{{ message | safe }}</p>
                <small class="d-sm-none m-0 p-0">{{ message | safe }}</small>
            </div>
        {% endfor %}
        
    {% endif %}

{% endwith %}

app/templates/core/_macros.html
<!-- Put your reusable template code into macros here -->

{% macro input(name, value='', type='text', size=20) -%}
    <input type="{{ type }}" name="{{ name }}" value="{{value|e }}" size="{{ size }}">
{%- endmacro %}

app/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <link rel="icon" href="{{ url_for('static', filename='img/favicon.png') }}" type="image/png">

  <title>{{ config.APP_NAME }}</title>

  <!-- TODO define styles -->
  <!-- meta -->
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width,initial-scale=1">

  {% block meta %}{% endblock %}


  <!-- TODO define links such as styles -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
  <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet" media="screen">

  {% block links %}{% endblock %}

</head>

<body style="background-color: rgb(243, 240, 214);" class="w-100 d-inline">

  {% include 'components/header.html' %}

  <div class="row">
    <div class="container my-5 col-11 col-xl-7 col-lg-8 col-md-9 col-sm-10 mx-auto">

      <!--  Flash messages -->
      {% include 'components/messages.html' %}

      <!-- Main Content -->

      {% block content %}{% endblock %}

    </div>
  </div>

  {% include 'components/footer.html' %}

app/templates/detail.html
{% extends 'core/base.html' %}

{% block content %}

<h2>Detalle Tarjeta</h2>
<hr>

<div class="col-xl-8 col-lg-8 col-md-10 col-sm-12 col-xs-12 mx-auto">

    {% if card %}

    <div class="form-row">
        <div class="form-group col-lg-12">
            <label for="input_radicado">Radicado</label>
            <input type="text" class="form-control" id="input_radicado" name="radicado" value="{{card.radicado}}"
                readonly>
        </div>

        {% if tail_transaction_hash %}
        <div class="form-group col-lg-12">
            <label for="input_tail_transaction_hash">IOTA Transaction Hash</label>
            <input type="text" class="form-control" id="input_tail_transaction_hash" name="tail_transaction_hash"
                value="{{tail_transaction_hash}}" readonly>
        </div>
        {% endif %}

    </div>
    <hr>

    <label><b>Vehiculo</b></label>
    <div class="form-row">
        <div class="form-group col-lg-6 col-sm-6">
            <label for="input_placa">Placa</label>
            <input type="text" class="form-control" id="input_placa" name="placa_vehiculo"
                value="{{card.placa_vehiculo}}" readonly>
        </div>
        <div class="form-group col-lg-6 col-sm-6">
            <label for="input_placa">Nº Tarjeta</label>
            <input type="number" class="form-control" id="input_tarjeta_vehiculo" name="tarjeta_vehiculo"
                value="{{card.tarjeta_vehiculo}}" readonly>
        </div>
    </div>
    <hr>

    <label><b>Tarjeta Operación</b></label>
    <div class="form-row">
        <div class="form-group col-lg-6">
            <label>Número</label>
            <input type="text" class="form-control" id="numero" name="numero" value="{{card.numero_tarjeta_operacion}}"
                readonly>
        </div>
        <div class="form-group col-lg-6">
            <label for="input_fecha_vencimiento">Fecha Vencimiento</label>
            <input type="text" class="form-control" id="fecha_vencimiento" name="fecha_vencimiento"
                value="{{card.fecha_vencimiento}}" readonly>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-lg-6">
            <label for="input_fecha_vencimiento">Fecha Inicio Vigencia</label>
            <input type="text" class="form-control" id="fecha_vencimiento" name="fecha_vencimiento"
                value="{{card.fecha_inicio_vigencia}}" readonly>
        </div>
        <div class="form-group col-lg-6">
            <label for="input_fecha_renovacion">Fecha Fin Vigencia</label>
            <input type="text" class="form-control" id="fecha_renovacion" name="fecha_renovacion"
                value="{{card.fecha_fin_vigencia}}" readonly>
        </div>
    </div>


    <hr>
    <label><b>Conductor</b></label>
    <div class="form-row">
        <div class="form-group col-lg-5">
            <label>Tipo de Documento</label>
            <input type="text" class="form-control" id="input_cedula" name="documento_conductor"
                value="{{card.tipo_documento_conductor}}" readonly>
        </div>
        <div class="form-group col-lg-7">
            <label>Número Documento</label>
            <input type="text" class="form-control" id="input_cedula" name="documento_conductor"
                value="{{card.documento_conductor}}" readonly>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-lg-12">
            <label>Nombre</label>
            <input type="text" class="form-control" id="input_nombre" name="nombre_conductor"
                value="{{card.nombre_conductor}}" readonly>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-lg-12">
            <label>Licencia Nº</label>
            <input type="number" class="form-control" id="input_nombre" name="licencia_conductor"
                value="{{card.licencia_conductor}}" readonly>
        </div>
    </div>
    <hr>

    <br>

    {% endif %}

    <div class="form-row d-flex justify-content-center">
        <a href="{{ url_for('card.explorer') }}" class="btn btn-outline-warning rounded col-4">Atras</a>
    </div>

</div>


<br>

{% endblock %}

app/templates/error.html
{% extends 'core/base.html' %}

{% block content %}
<div class="jumbotron my-4 bg-warning">
  <div class="text-center">
    <h1>{{ '%s - %s' % (error.code, error.name) }}</h1>
    <p>{{ error.description }}.</p>
  </div>
</div>
{% endblock %}

app/templates/explorer.html
{% extends 'core/base.html' %}

{% block content %}

<h2>Consultar una Tarjeta</h2>
<hr>

<div class="table-responsive">
    <table class="table table-hover table-sm" id="tabla">
        <thead>
            <tr class="d-flex">
                <th colspan=1 scope="col" class="border-top-0 col-3 d-flex justify-content-center ">
                    Radicado
                </th>
                <th colspan=1 scope="col" class="border-top-0 col-1 d-flex justify-content-center">
               
                </th>
                <th colspan=1 scope="col" class="border-top-0 col-7 d-flex justify-content-center">
                    Tail Transaction Hash
                </th>
                <th colspan=1 scope="col" class="border-top-0 col-1 d-flex justify-content-center">
                    
                </th>
            </tr>

        </thead>

        {% if transaction_list %}
        <tbody>
            {% for transaction in transaction_list %}
            <tr class="d-flex">
                <td class="col-3">
                    <p class="text-ellipsis">{{ transaction.radicado }}</p>
                </td>
                <td class="col-1">
                    <form action="{{url_for('card.detail', query_type='db', identifier=transaction.radicado )}}" method="GET">
                        <button type="submit" class="btn btn-outline-warning btn-sm p-1 m-0 w-50 rounded" title="Ver en la Base de Datos">
                            <img src="{{ url_for('static', filename='img/database.png') }}" alt="Ver en la Base de Datos"
                            width="60%" height="70%"/>
                        </button>
                    </form>
                </td>

                <td class="col-7">
                    <p class="text-ellipsis">{{ transaction.tail_transaction_hash }}</p>
                </td>
                <td class="col-1 row d-flex justify-content-end">
                    <form action="{{url_for('card.detail', query_type='tangle', identifier=transaction.tail_transaction_hash )}}" method="GET">
                        <button type="submit" class="btn btn-outline-warning btn-sm p-1 m-0 w-50 rounded" title="Ver en el Tangle">
                            <img src="{{ url_for('static', filename='img/favicon.png') }}" alt="Ver en el tangle"
                            width="80%" height="90%"/>
                        </button>
                        
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        {% endif %}
    </table>
    <!-- END - ORDERS LISTING  -->
</div>

<br>

{% endblock %}

app/templates/index.html
{% extends 'core/base.html' %}

{% block content %}


<h1 ><span class="text-warning">TARJETA AMARILLA </span> IOTA DLT!</h1>
<hr>
<div class="container w-100">
  <div class="row">
    <div class="col-7">
      <a href="iota.org" class="text-warning" target="_blank">IOTA</a> es una tecnología de contabilidad distribuida de código abierto, cuyo objetivo es permitir de forma segura el
      intercambio de warningrmación y valor en el Internet de las Cosas.
      <br><br>
      Además de ser una criptomoneda muy segura y fácil para transar, <a href="iota.org" class="text-warning" target="_blank">IOTA</a> tiene aplicaciones en ciudades inteligentes,
      movilidad, identidad digital, impacto social y comercio global.
      <br><br>
      <a href="iota.org" class="text-warning" target="_blank">IOTA</a> es open source, un “blockchain”, una capa de confianza, un protocolo de IoT, un DLT escalable y no tiene
      tarifas de mineros.
      

    </div>
    <div class="col-5">
      <img src="{{ url_for('static', filename='img/iota_tangle.png') }}" alt="" width="55%" height="90%">
    </div>
  </div>
  <div class="row p-3"></div>
  <div class="row">
    <div class="col-4">
      <img src="{{ url_for('static', filename='img/taxi-icon.png') }}" alt="" width="80%" height="100%">
    </div>
    <div class="col-8">
      
      Esta Web App tiene como funcionalidades principales demostrar la escritura y lectura de transacciones en una red
      privada de <a href="iota.org" class="text-warning" target="_blank">IOTA</a> o Private Tangle, por medio de consultas y registros en a un servicio web Rest expuesto por la
      red.
      <br><br>
      Además, se evidencia la inmutabilidad y seguridad de datos que brindan los DLT´s a comparación de los otros
      sistemas de almacenamiento tradicionales, como bases de datos transaccionales y archivos estáticos planos.
      <br><br>
      En la parte superior derecha podrás encontrar los accesos nuestras funcionalidades para interactuar con el Private
      Tangle.

    </div>
  </div>
</div>
<p class="px-2">
  <br>

  <i>
    Desarrollado en
    <a href="https://www.python.org/" target="_blank" class="text-warning">Python</a>
    <a href="https://flask.palletsprojects.com/" target="_blank" class="text-warning">Flask</a>
    <!-- por
    <a href="https://gitlab.com/juanesquintero/" target="_blank" class="text-warning"><b>juanesquintero</b></a>. -->

    <br>
    Agradecimientos especiales a la comunidad
    <a href="https://www.iota.org/" target="_blank" class="text-warning"><a href="iota.org" class="text-warning" target="_blank">IOTA</a> Foundation </a>
    que hace este proyecto posible.
  </i>
</p>
<br>

{% endblock %}

app/templates/registry.html
{% extends 'core/base.html' %}

{% block content %}

<h2 class="">Tarjeta de Control</h2>
<hr>

<div class="row w-100">
    <form method="POST" action="{{url_for('card.registry')}}" class="col-lg-8 col-sm-12 mx-auto">

        <div class="form-row">
            <div class="form-group col-lg-12">
                <label for="input_radicado"><b>Radicado</b></label>
                <input type="text" class="form-control bg-light" id="input_radicado" name="radicado" value="{{radicado}}"
                    readonly required>
            </div>
    
        </div>
        <hr>
    
        <label><b>Vehiculo</b></label>
        <div class="form-row">
            <div class="form-group col-lg-6">
                <label for="input_placa">Placa</label>
                <input type="text" class="form-control" id="input_placa" name="placa_vehiculo" placeholder="ABC123" required>
            </div>
            <div class="form-group col-lg-6">
                <label for="input_placa">Nº Tarjeta</label>
                <input type="number" class="form-control" id="input_tarjeta_vehiculo" name="tarjeta_vehiculo" placeholder="01" required>
            </div>
        </div>
        <hr>
    
        <label><b>Tarjeta Operación</b></label>
        <div class="form-row">
            <div class="form-group col-lg-6">
                <label>Número</label>
                <input type="number" class="form-control" id="input_numero_tarjeta" name="numero_tarjeta_operacion" placeholder="123456789" required>
            </div>
            <div class="form-group col-lg-6">
                <label for="input_fecha_vencimiento">Fecha Vencimiento</label>
                <input type="date" class="form-control" id="input_fecha_vencimiento" name="fecha_vencimiento" required>
            </div>
        </div>
    
        <div class="form-row">
            <div class="form-group col-lg-6">
                <label for="input_fecha_renovacion">Fecha Inicio Vigencia</label>
                <input type="date" class="form-control" id="input_fecha_renovacion" name="fecha_inicio_vigencia" required>
            </div>
            <div class="form-group col-lg-6">
                <label for="input_fecha_renovacion">Fecha Fin Vigencia</label>
                <input type="date" class="form-control" id="input_fecha_renovacion" name="fecha_fin_vigencia" required>
            </div>
        </div>
    
    
        <hr>
        <label><b>Conductor</b></label>
        <div class="form-row">
            <div class="form-group col-lg-5">
                <label>Tipo de Documento</label>
                <select id="input_tipo_documento_conductor" name="tipo_documento_conductor" class="form-control" required>
                    {% for id_type in dni_types %}
                    <option value="{{id_type}}">{{id_type}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group col-lg-7">
                <label>Número Documento</label>
                <input type="number" class="form-control" id="input_documento_conductor" name="documento_conductor" placeholder="123456789" required>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-lg-12">
                <label>Nombres y Apellidos</label>
                <input type="text" class="form-control" id="input_nombre_conductor" name="nombre_conductor" placeholder="Pepe Perez Sosa"
                    required>
            </div>
            <div class="form-group col-lg-12">
                <label>Licencia Nº</label>
                <input type="number" class="form-control" id="input_licencia_conductor" name="licencia_conductor" placeholder="123456789"
                    required>
            </div>
        </div>
        <hr>
    
    
        <div class="form-row d-flex justify-content-center">
            <div class="col-4">
            </div>
        </div>
    
        <br>
    
        <div class="form-row d-flex justify-content-center">
            <button type="submit" class="btn btn-outline-warning rounded col-4">Enviar</button>
        </div>
    
    </form>
</div>


<br>

{% endblock %}